### PR TITLE
Changed script src from current dir to base dir of the project

### PR DESCRIPTION
**Pull request by hugofree17**
## Description

It was a very simple change and so not needed and this change is not able to be tested so well.
Just removed ./ to not target the current dir but yes the base dir of the project.

## Motivation and context

I noticed an issue when I was targeting a route like admin/dashboard.
It was looking for app.js inside the admin dir and not in the base one.

## How has this been tested?

After made the change I refreshed the page and tested with several routes and all went fine.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by clebersa** [comment]
Hi @hugofree17,

This was a recent change. I proposed a pull request (https://github.com/acacha/adminlte-laravel/pull/218) 3 days ago fixing the URL for some resources and this was one of the URLs I changed. I added the `./` because I serve my application using an alias with Apache and, without that string, an 404 error is thrown. When I made the change, I tested the new URL with and without alias and it worked. So, my intention was trying to find a URL that would work for both ways of serving an application.

However, as you found out, it does not work for nested links. In fact, when I tested my changes, I did not test nested links and that's why I did not found the same problem as you.

I am still trying to find a way that work for both cases. I found one solution and I would like you to test it to see if it works for you too. Try referencing `app.js` like this:
```html
<script src="{{ URL::to('/') . mix('/js/app.js') }}" type="text/javascript"></script>
```

The `to()` function gets the URL for some path and, in this case, for the base URL for the application. As far as I tested here, including nested links, it works. I would like to know if it works for you too and then @acacha could tell what he thinks about the change. Then we could proceed with the pull request by updating it (or not) and then approving it.

In case you the change I propose works, could you please do the same for `resources/views/vendor/adminlte/layouts/landing.blade.php`, which references `app-landing.js` the same way?

Thanks for your finding.
Have a good night.
Bye.

**Comment by hugofree17** [comment]
Hello @clebersa,

Thanks for your message.
I did the change you proposed and it worked without any error, in both script references.
I'm using Homestead (Nginx) so that approach works for both app serving ways.

So I hope @acacha can tell something about it to see if we proceed with a pull request or not.

**Comment by clebersa** [comment]
Hi @hugofree17,

That is good. Thank you for trying that implementation.

Let's wait for @acacha's decision then.

Have a good weekend!

**Comment by acacha** [comment]
Sorry for the delay... I push a new commit with a similar solution like clebersa one. Thanks!

**Comment by acacha** [comment]
https://github.com/acacha/adminlte-laravel/commit/407ec5351a95df19f06f6e52dd8676fca4b46e73

**Pull request closed without merging**
